spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: petclinic
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
        - id: grafana
          uri: http://localhost:8083
          predicates:
            - Path=/analytics/**
        - id: petclinic-auth
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
