apiVersion: v1
data:
  application.yml: |
    spring:
      application:
        name: api-gateway

      cloud:
        gateway:
          routes:
            - id: petclinic
              uri: http://petclinic:8080
              predicates:
                - Path=/api/**
            - id: grafana
              uri: http://grafana:3000
              predicates:
                - Path=/grafana/**
            - id: prometheus
              uri: http://prometheus:9090
              predicates:
                - Path=/prometheus/**
            - id: auth-service
              uri: http://auth-service:8080
              predicates:
                - Path=/authenticate/**
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: api-gateway
  name: api-gateway-cm0
