name: ci-cd

on:
  push:
    branches:
      - staging

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: mustafadocker1/gateway:staging

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Kubeconfig dosyasını ayarla
      - name: Set up Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          echo "${{ secrets.KUBE_CACRT }}" > ~/.kube/ca.crt
          echo "${{ secrets.KUBE_CLIENTCRT }}" > ~/.kube/client.crt
          echo "${{ secrets.KUBE_CLIENTKEY }}" > ~/.kube/client.key

      # Kubernetes'e Deployment yap
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./deployment/api-gateway-cm0-configmap.yaml
          kubectl apply -f ./deployment/api-gateway-deployment.yaml
          kubectl apply -f ./deployment/api-gateway-service.yaml